# Generated by Django 4.2.2 on 2023-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=150)),
                ('ingredients', models.ManyToManyField(to='main_app.ingredients')),
            ],
        ),
    ]
