# Generated by Django 4.2.2 on 2023-07-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ingredientslist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsList',
            new_name='Shopping_Lists',
        ),
    ]
