# Generated by Django 4.2.2 on 2023-07-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_ingredientslist_shopping_lists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_Lists',
            new_name='ShoppingLists',
        ),
        migrations.AlterModelOptions(
            name='shoppinglists',
            options={'ordering': ['list_name']},
        ),
    ]
